### ISSUE TITLE
Image Doesn't Fill Entire Board View When Using Layout Constraints

### ISSUE THREAD

**Issue by raginggoat** [ikhsan/IXNTilePuzzle#3]
I am trying to use this with layout constraints in order to support all iPhone screen sizes. The puzzle works, but the image for the puzzle does not use the entire frame of the board view. If I remove the constraints on the board view, the image uses the entire size, but the board is not in the correct location on all screen sizes. Any ideas?
![ios simulator screen shot apr 13 2015 2 43 48 pm](https://cloud.githubusercontent.com/assets/4974456/7122769/8d17cfb4-e1eb-11e4-8419-c569d0bcb525.png)

**Comment by ixnixnixn** [comment]
what iOS and device do you use for your project? If you could share the project's information I could have a better look.

**Comment by eldesperado** [comment]
Actually, in IXNTileBoardView class, he tries to get a resized image. However, as using auto layout, IXNTileBoardView's size is resized because of its constraints. Thus, you get the wrong size.

So if what you want is the actual size of IXNTileBoardView implied by your existing constraints, you can not inspect this size manually. Instead, you can ask autolayout to update the layout for you by using this [view layoutIfNeeded].

Just add [view layoutIfNeeded] right before getting the resized image.

**Comment by ikhsan** [comment]
I'm assuming that it's a problem that revolves around the constraint. As no reply from the enquirer for 6 months, I'm going to close this off. 

@raginggoat Feel free to enquire back with the answer of my question.
